sudo: required

language: python

python:
  - "3.6"

services:
  - docker

git:
  depth: 1

branches:
  only:
    - master

env:
  global:
    # Variables found by default in Docker Hub builder
    - DOCKER_REPO=tecnativa/odoo-base
    - DOCKER_TAG=latest
    - IMAGE_NAME=$DOCKER_REPO:$DOCKER_TAG
  matrix:
    - ODOO_VERSIONS=8.0
    - ODOO_VERSIONS=9.0
    - ODOO_VERSIONS=10.0
    - ODOO_VERSIONS=11.0

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::=--force-confnew install docker-ce
  - pip install -r requirements-ci.txt

install:
  - ./hooks/build

script:
  - python -m unittest -v tests
