version: "2.1"
services:
    odoo:
        extends:
            file: common.yaml
            service: odoo
        build:
            args:
                PGDATABASE: test
                # You may want demo data for testing
                WITHOUT_DEMO: "false"
        depends_on:
            - db
            - smtp
            - inbox
        networks:
            default:
            inverseproxy_shared:
        labels:
            traefik.longpolling.frontend.rule:
                "Host:${DOMAIN_TEST};PathPrefix:/longpolling/"
            traefik.www.frontend.rule: "Host:${DOMAIN_TEST}"
        command:
            - odoo
            - --workers=2
            - --max-cron-threads=1

    db:
        extends:
            file: common.yaml
            service: db

    inbox:
        extends:
            file: common.yaml
            service: inboxfake

    smtp:
        extends:
            file: common.yaml
            service: smtpfake

networks:
    default:
        driver_opts:
            encrypted: 1

    inverseproxy_shared:
        external: true

volumes:
    # XXX Odoo volume names must match $ODOO_MAJOR for quick branch switching
    filestore10:
    db10:
